[package]
name = "counter2"
version = "0.1.1"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>", "Jesse McDonald <nybble41@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
iced = "0.3"
